version: '3.8'
services:

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  blog-dynamic: 
    image: discoduroderoer/blog-dynamic:v1
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    command: npm run start:prod
    depends_on:
      - mongodb

volumes:
  mongodb_data_container: